import Groq from "groq-sdk";
import puppeteer from "puppeteer";
import "dotenv/config";

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

async function generateInterviewReportFromAi({
  resume,
  selfDescription,
  jobDescription,
}) {
  
  const prompt = `
        Analyze the following candidate details and generate a structured interview report in JSON format.
        
        Resume: ${resume}
        Self Description: ${selfDescription}
        Job Description: ${jobDescription}

        The output MUST be a valid JSON object matching this structure:
        {
            "matchScore": number (0-100),
            "technicalQuestions": [{"question": string, "intention": string, "answer": string}],
            "behaviouralQuestions": [{"question": string, "intention": string, "answer": string}],
            "skillGaps": [{"skill": string, "severity": "low" | "medium" | "high"}],
            "preparationPlan": [{"day": number, "focus": string, "tasks": [string]}],
            "title": string (Job Title)
        }
    `;
  const chatCompletion = await groq.chat.completions.create({
    messages: [{ role: "user", content: prompt }],
    model: "llama-3.3-70b-versatile",
    response_format: { type: "json_object" }, // Forces JSON output
  });

  return JSON.parse(chatCompletion.choices[0].message.content);
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {
  const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `;

  const chatCompletion = await groq.chat.completions.create({
    messages: [{ role: "user", content: prompt }],
    model: "llama-3.3-70b-versatile",
    response_format: { type: "json_object" },
  });

  const jsonContent = JSON.parse(chatCompletion.choices[0].message.content);
  return await generatePdfFromHtml(jsonContent.html);
}

async function generatePdfFromHtml(htmlContent) {
  const browser = await puppeteer.launch({ headless: "new" });
  const page = await browser.newPage();
  await page.setContent(htmlContent, { waitUntil: "networkidle0" });

  const pdfBuffer = await page.pdf({
    format: "A4",
    margin: { top: "20mm", bottom: "20mm", left: "15mm", right: "15mm" },
  });

  await browser.close();
  return pdfBuffer;
}

export { generateInterviewReportFromAi, generateResumePdf };
